server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rockycta/automobile-configrepo.git
          default-label: master
  application:
    name: ConfigServer
  security:
    user:
      name: configadmin
      password: welcome1
      roles:
      - admin
