server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://rockycta: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@github.com/Rockycta/automobile-configrepo.git
          default-label: master
  application:
    name: ConfigServer
  security:
    user:
      name: configadmin
      password: welcome1
      roles:
      - admin
